# Generated by Django 5.1.4 on 2024-12-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryform', '0004_alter_enquiryform_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='projectimg/')),
                ('project', models.CharField(max_length=500)),
                ('project_link', models.CharField(max_length=500)),
                ('about', models.TextField()),
            ],
        ),
    ]
