# Generated by Django 5.1.4 on 2024-12-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiryform', '0005_projectsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projectsdata',
        ),
    ]
